### ISSUE TITLE
RuboCop version 1.55.1 is not supported by CodeClimate.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-style#35]
I tried doing a `manageiq-stlyle --install` in another project to see if the files would update and was given the error

```
RuboCop version 1.55.1 is not supported by CodeClimate.
```

but I'm not sure what that means or how to deal with it.

**Comment by bdunne** [comment]
It's looking for the codeclimate-rubocop channel/rubocop-1-55-1 branch, but there isn't one yet.  The latest appears to be 1.50.2 so I think that's the latest version of rubocop you can use
https://github.com/codeclimate/codeclimate-rubocop/branches/all?query=channel%2Frubocop-1-5
