### ISSUE TITLE
Blast out changes to all repos for the codeclimate channel

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-style#44]
- [x] https://github.com/ManageIQ/activerecord-id_regions/pull/34
- [x] https://github.com/ManageIQ/activerecord-virtual_attributes/pull/134
- [x] https://github.com/ManageIQ/amazon_ssa_support/pull/109
- [x] https://github.com/ManageIQ/awesome_spawn/pull/74
- [x] https://github.com/ManageIQ/azure-armrest/pull/429
- [x] https://github.com/ManageIQ/azure-signature/pull/13
- [x] https://github.com/ManageIQ/binary_struct/pull/27
- [x] https://github.com/ManageIQ/bundler-inject/pull/37
- [x] https://github.com/ManageIQ/dbus_api_service/pull/39
- [x] https://github.com/ManageIQ/ffi-vix_disk_lib/pull/35
- [x] https://github.com/ManageIQ/foreman_api_client/pull/26
- [x] https://github.com/ManageIQ/httpd_configmap_generator/pull/79
- [x] https://github.com/ManageIQ/inventory_refresh/pull/123
- [x] https://github.com/ManageIQ/linux_admin/pull/242
- [x] https://github.com/ManageIQ/linux_block_device/pull/13
- [x] https://github.com/ManageIQ/log_decorator/pull/26
- [x] https://github.com/ManageIQ/manageiq/pull/22928
- [x] https://github.com/ManageIQ/manageiq-api/pull/1252
- [x] https://github.com/ManageIQ/manageiq-api-client/pull/116
- [x] https://github.com/ManageIQ/manageiq-appliance_console/pull/237
- [x] https://github.com/ManageIQ/manageiq-automation_engine/pull/543
- [x] https://github.com/ManageIQ/manageiq-consumption/pull/216
- [x] https://github.com/ManageIQ/manageiq-content/pull/741
- [x] https://github.com/ManageIQ/manageiq-cross_repo/pull/105
- [x] https://github.com/ManageIQ/manageiq-decorators/pull/101
- [x] https://github.com/ManageIQ/manageiq-gems-pending/pull/573
- [x] https://github.com/ManageIQ/manageiq-loggers/pull/66
- [x] https://github.com/ManageIQ/manageiq-messaging/pull/85
- [x] https://github.com/ManageIQ/manageiq-password/pull/38
- [x] https://github.com/ManageIQ/manageiq-postgres_ha_admin/pull/44
- [x] https://github.com/ManageIQ/manageiq-providers-amazon/pull/847
- [x] https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/308
- [x] https://github.com/ManageIQ/manageiq-providers-autosde/pull/246
- [x] https://github.com/ManageIQ/manageiq-providers-awx/pull/28
- [x] https://github.com/ManageIQ/manageiq-providers-azure/pull/551
- [x] https://github.com/ManageIQ/manageiq-providers-azure_stack/pull/105
- [x] https://github.com/ManageIQ/manageiq-providers-cisco_intersight/pull/109
- [x] https://github.com/ManageIQ/manageiq-providers-dummy_provider/pull/58
- [x] https://github.com/ManageIQ/manageiq-providers-foreman/pull/126
- [x] https://github.com/ManageIQ/manageiq-providers-google/pull/262
- [x] https://github.com/ManageIQ/manageiq-providers-ibm_cic/pull/46
- [x] https://github.com/ManageIQ/manageiq-providers-ibm_cloud/pull/488
- [x] https://github.com/ManageIQ/manageiq-providers-ibm_power_hmc/pull/156
- [x] https://github.com/ManageIQ/manageiq-providers-ibm_power_vc/pull/105
- [x] https://github.com/ManageIQ/manageiq-providers-ibm_terraform/pull/104
- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/521
- [x] https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/232
- [x] https://github.com/ManageIQ/manageiq-providers-lenovo/pull/403
- [x] https://github.com/ManageIQ/manageiq-providers-nsxt/pull/100
- [x] https://github.com/ManageIQ/manageiq-providers-nuage/pull/307
- [x] https://github.com/ManageIQ/manageiq-providers-openshift/pull/258
- [x] https://github.com/ManageIQ/manageiq-providers-openstack/pull/876
- [x] https://github.com/ManageIQ/manageiq-providers-oracle_cloud/pull/99
- [x] https://github.com/ManageIQ/manageiq-providers-ovirt/pull/661
- [x] https://github.com/ManageIQ/manageiq-providers-red_hat_virtualization/pull/45
- [x] https://github.com/ManageIQ/manageiq-providers-redfish/pull/191
- [x] https://github.com/ManageIQ/manageiq-providers-vmware/pull/903
- [x] https://github.com/ManageIQ/manageiq-providers-workflows/pull/72
- [x] https://github.com/ManageIQ/manageiq-rpm_build/pull/448
- [x] https://github.com/ManageIQ/manageiq-schema/pull/723
- [x] https://github.com/ManageIQ/manageiq-smartstate/pull/182
- [x] https://github.com/ManageIQ/manageiq-ssh-util/pull/19
- [x] https://github.com/ManageIQ/manageiq-ui-classic/pull/9106
- [x] https://github.com/ManageIQ/memory_buffer/pull/22
- [x] https://github.com/ManageIQ/mime-types-redirector/pull/6
- [x] https://github.com/ManageIQ/miq_bot/pull/676
- [x] https://github.com/ManageIQ/more_core_extensions/pull/117
- [x] https://github.com/ManageIQ/multi_repo/pull/25
- [x] https://github.com/ManageIQ/net_app_manageability/pull/20
- [x] https://github.com/ManageIQ/optimist/pull/143
- [x] https://github.com/ManageIQ/ovirt/pull/110
- [x] https://github.com/ManageIQ/ovirt_metrics/pull/50
- [x] https://github.com/ManageIQ/pg-dsn_parser/pull/22
- [x] https://github.com/ManageIQ/pg-logical_replication/pull/23
- [x] https://github.com/ManageIQ/query_relation/pull/32
- [x] https://github.com/ManageIQ/vmware_web_service/pull/128
- [x] https://github.com/ManageIQ/wim_parser/pull/11

**Comment by Fryguy** [comment]
cc @agrare @jrafanie @bdunne @kbrock 

This may cause repos to go "red" for CodeClimate because it will actually find newer things that are in the newer codeclimate.

I wish there was a way to have central configuration for this particular thing, but I don't think codeclimate supports that :(

**Comment by Fryguy** [comment]
@agrare @jrafanie @bdunne @kbrock I am seeing some common codeclimate patterns that I think we can fix with a few simple decisions.  Please let me know your thoughts and then I can make the necessary changes.

1. https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdevelopmentdependencies

   This defaults to "Gemfile", meaning they don't want to see development dependencies in the gemspec.  Personally, I think that's weird, and I see nothing wrong with .gemspec.  In fact, when it's in gemspec you can then also see it in rubygems.org.  I can't find anything in the Ruby style guide about this decision.  Discussion about it was here (`https://github.com/rubocop/rubocop/pull/11469`), and the choice of default was rather abitrary, which quite a few against.

   I'm leaning towards changing the default for this to .gemspec or even disabling it altogether

2. https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecrequiremfa

   I'm ok with this one, and it would be trivial to blast this out to all of our gems.  If you agree I'll do it.

3. https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecrequiredrubyversion

   While I would like to keep this one and think we should set it everywhere, the way they designed this is that the TargetRubyVersion must match the minimum specified in the gemspec, so since we set our TargetRubyVersion to 3.0, we'd be required to do required_ruby_version >= 3.0, and I don't like that

   I'm leaning towards disabling this cop.

**Comment by kbrock** [comment]
1. I prefer dev gems in the gemspec (except for byebug) - Gemfile should be used for pegging a dev environment and not for dependencies. **default to gemspec** (Sometimes you need to peg the rails version, so maybe disabling is the way to go)
2. I tended not to go this route, but not my hill. **blast to yes**
3. Yes, I like to set ruby version in every gem. Agree we want to set our own preferences though. **disable**

**Comment by jrafanie** [comment]
1.  I also think gemspec is fine.  I forgot but apparently, you can also install a gems dev dependencies: `gem install --dev your_gem`.  That goes along with the niceties of showing people in rubyems.org.  Honestly, I think Gemfile is nice for stuff you're hacking on or debugging but once you want to publish the gem, any dev dependencies you actively use should probably be promoted to the gemspec as such.  Either way, I don't think this is something we really care about flagging.
2. Sure.  Not a big deal but we should do that. Blast away.
3. This might be branch specific.  I'm fine with enforcing the minor ruby version on release branches but on master, we should ignore this.
4.

**Comment by kbrock** [comment]
all issues have been merged.
